// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDIymoSdT1pfTd6ydVpOpGxA8jDXqyqZ8',
    appId: '1:990525255496:web:0725681c60e91008918d7d',
    messagingSenderId: '990525255496',
    projectId: 'adamultiapp',
    authDomain: 'adamultiapp.firebaseapp.com',
    storageBucket: 'adamultiapp.appspot.com',
    measurementId: 'G-Q8FRWP1KS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlUuI8RUSAmQV6klLi5fNVV9g6G38O6xY',
    appId: '1:990525255496:android:dce4611b2ddb7d20918d7d',
    messagingSenderId: '990525255496',
    projectId: 'adamultiapp',
    storageBucket: 'adamultiapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC627rG6YJgIl9nTicy-kAeVfA9JYP0JrM',
    appId: '1:990525255496:ios:08049415eb015ef4918d7d',
    messagingSenderId: '990525255496',
    projectId: 'adamultiapp',
    storageBucket: 'adamultiapp.appspot.com',
    androidClientId: '990525255496-1o3drh225fqqbr1vhvadn9ok8579omcb.apps.googleusercontent.com',
    iosClientId: '990525255496-65or3doqakts4h1he6m67mactuld6apv.apps.googleusercontent.com',
    iosBundleId: 'com.example.adamultiMobileCloneNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC627rG6YJgIl9nTicy-kAeVfA9JYP0JrM',
    appId: '1:990525255496:ios:683b52f22c018ee5918d7d',
    messagingSenderId: '990525255496',
    projectId: 'adamultiapp',
    storageBucket: 'adamultiapp.appspot.com',
    androidClientId: '990525255496-1o3drh225fqqbr1vhvadn9ok8579omcb.apps.googleusercontent.com',
    iosClientId: '990525255496-lr2rqlhcp4ahlnhme0efs591alc6gbht.apps.googleusercontent.com',
    iosBundleId: 'com.example.adamultiMobileCloneNew.RunnerTests',
  );
}
