import "package:adamulti_mobile_clone_new/cubit/authenticated_cubit.dart";
import "package:adamulti_mobile_clone_new/cubit/bottom_navigation_cubit.dart";
import "package:adamulti_mobile_clone_new/cubit/connected_devices_cubit.dart";
import "package:adamulti_mobile_clone_new/cubit/getme_cubit.dart";
import "package:adamulti_mobile_clone_new/cubit/google_account_cubit.dart";
import "package:adamulti_mobile_clone_new/cubit/inbox_schema_cubit.dart";
import "package:adamulti_mobile_clone_new/cubit/notification_count_cubit.dart";
import "package:adamulti_mobile_clone_new/cubit/setting_applikasi_cubit.dart";
import "package:adamulti_mobile_clone_new/cubit/user_appid_cubit.dart";
import "package:adamulti_mobile_clone_new/services/auth_service.dart";
import "package:adamulti_mobile_clone_new/services/backoffice_service.dart";
import "package:adamulti_mobile_clone_new/services/firebase_messaging_service.dart";
import "package:adamulti_mobile_clone_new/services/history_service.dart";
import "package:adamulti_mobile_clone_new/services/jwt_service.dart";
import "package:adamulti_mobile_clone_new/services/komisi_service.dart";
import "package:adamulti_mobile_clone_new/services/local_notification_service.dart";
import "package:adamulti_mobile_clone_new/services/notification_service.dart";
import "package:adamulti_mobile_clone_new/services/product_service.dart";
import "package:adamulti_mobile_clone_new/services/region_service.dart";
import "package:adamulti_mobile_clone_new/services/reward_service.dart";
import "package:adamulti_mobile_clone_new/services/secure_storage.dart";
import "package:adamulti_mobile_clone_new/services/topup_service.dart";
import "package:adamulti_mobile_clone_new/services/transaction_service.dart";
import "package:get_it/get_it.dart";

final locator = GetIt.instance;

void setupLocator() {
  locator.registerLazySingleton(() => AuthService());
  locator.registerLazySingleton(() => BackOfficeService());
  locator.registerLazySingleton(() => SecureStorageService());
  locator.registerSingleton(BottomNavigationCubit());
  locator.registerSingleton(InboxSchemaCubit());
  locator.registerSingleton(AuthenticatedCubit());
  locator.registerSingleton(UserAppidCubit());
  locator.registerSingleton(GetmeCubit());
  locator.registerSingleton(GoogleAccountCubit());
  locator.registerSingleton(NotificationCountCubit());
  locator.registerSingleton(SettingApplikasiCubit());
  locator.registerSingleton(ConnectedDevicesCubit());
  locator.registerLazySingleton(() => JwtService());
  locator.registerLazySingleton(() => ProductService());
  locator.registerLazySingleton(() => TransactionService());
  locator.registerLazySingleton(() => LocalNotificationService());
  locator.registerLazySingleton(() => TopupService());
  locator.registerLazySingleton(() => HistoryService());
  locator.registerLazySingleton(() => RewardService());
  locator.registerLazySingleton(() => KomisiService());
  locator.registerLazySingleton(() => RegionService());
  locator.registerLazySingleton(() => FirebaseMessagingService());
  locator.registerLazySingleton(() => NotificationService());
}